name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/upload-artifact@v7
        with:
          name: mxhx-minimalcomps-haxelib
          path: |
            src/
            haxelib.json
            include.xml
            mxhx-manifest.xml
            README.md
            LICENSE
            NOTICE
            CHANGELOG.md
          if-no-files-found: error
  ################################################################################
  # NOTE: we don't test the flash/air targets because the minimalcomps library is
  # not compatible with these targets
  ################################################################################
  tests-misc:
    strategy:
      matrix:
        haxe-version: [4.0.5, 4.1.5, 4.2.5, 4.3.7]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cedx/setup-hashlink@v3
      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
      - uses: krdlab/setup-haxe@v2
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Set up Haxelib dependencies
        run: |
          haxelib install utest --quiet
          haxelib install hxcpp --quiet
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install minimalcomps --quiet
          haxelib git bindable https://github.com/mxhx-dev/bindable.git --quiet
          haxelib git mxhx-component https://github.com/mxhx-dev/mxhx-component.git --quiet
          haxelib git mxhx-runtime-component https://github.com/mxhx-dev/mxhx-runtime-component.git --quiet
          haxelib dev mxhx-minimalcomps ${{ github.workspace }}
      - name: Run Neko Tests
        working-directory: test
        run: |
          haxelib run openfl test neko
      - name: Run HTML5 Tests
        working-directory: test
        run: |
          npm ci
          npx playwright install
          npx playwright install-deps
          haxelib run openfl build html5 -Dplaywright
          node playwright-runner.js
  tests-hashlink:
    strategy:
      matrix:
        haxe-version: [4.0.5, 4.1.5, 4.2.5, 4.3.7]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cedx/setup-hashlink@v3
      - uses: krdlab/setup-haxe@v2
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Set up Haxelib dependencies
        run: |
          haxelib install utest --quiet
          haxelib install hxcpp --quiet
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install minimalcomps --quiet
          haxelib git bindable https://github.com/mxhx-dev/bindable.git --quiet
          haxelib git mxhx-component https://github.com/mxhx-dev/mxhx-component.git --quiet
          haxelib git mxhx-runtime-component https://github.com/mxhx-dev/mxhx-runtime-component.git --quiet
          haxelib dev mxhx-minimalcomps ${{ github.workspace }}
      - name: Run HashLink Tests
        working-directory: test
        run: |
          haxelib run openfl test hl
  samples-misc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install minimalcomps --quiet
          haxelib git bindable https://github.com/mxhx-dev/bindable.git --quiet
          haxelib git mxhx-component https://github.com/mxhx-dev/mxhx-component.git --quiet
          haxelib git mxhx-runtime-component https://github.com/mxhx-dev/mxhx-runtime-component.git --quiet
          haxelib dev mxhx-minimalcomps ${{ github.workspace }}
      - name: Build samples/hello-world
        working-directory: samples/hello-world
        run: |
          haxelib run openfl build neko
          haxelib run openfl build html5
          haxelib run openfl build hl
      - name: Build samples/data-binding
        working-directory: samples/data-binding
        run: |
          haxelib run openfl build neko
          haxelib run openfl build html5
          haxelib run openfl build hl
      - name: Build samples/runtime-hello-world
        working-directory: samples/runtime-hello-world
        run: |
          haxelib run openfl build neko
          haxelib run openfl build html5
          haxelib run openfl build hl
