name: Samples

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build-misc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.3
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install minimalcomps --quiet
          haxelib git bindable https://github.com/mxhx-dev/bindable.git --quiet
          haxelib git mxhx-component https://github.com/mxhx-dev/mxhx-component.git --quiet
          haxelib git mxhx-runtime-component https://github.com/mxhx-dev/mxhx-runtime-component.git --quiet
          haxelib dev mxhx-minimalcomps $GITHUB_WORKSPACE
      - name: Build samples/hello-world
        working-directory: samples/hello-world
        run: |
          haxelib run openfl build neko
          haxelib run openfl build html5
          haxelib run openfl build hl
      - name: Build samples/data-binding
        working-directory: samples/data-binding
        run: |
          haxelib run openfl build neko
          haxelib run openfl build html5
          haxelib run openfl build hl
      - name: Build samples/runtime-hello-world
        working-directory: samples/runtime-hello-world
        run: |
          haxelib run openfl build neko
          haxelib run openfl build html5
          haxelib run openfl build hl
